### ISSUE TITLE
Which transcription standards are used?

### ISSUE THREAD

**Issue by jsbien** [kilobyte/tran#2]
Just curious :-)

Cf. e.g. PN-ISO 9-2000 (http://www.ebib.pl/biuletyn-ebib/16/a.php?bien)

**Comment by kilobyte** [comment]
Good idea to document that, I've added relevant comments to some of the data files.

When in doubt, I chosen usability and completeness over conformance to standards — a simple tool such as this is not going to be used by experts; my focus is on an ordinary person who tries to get a rough idea of a text in a foreign script.

Another concern is that, being aimed at an international user, *tran* targets English.  And English's correspondence between letters and phonemes is insane at best.  For this reason, there's no "right" answer — certainly not for an unsophisticated tool.  Thus, the quality is drastically lower: your research took serious effort even for a target language with a regular orthography such as Polish, while my quick hack tackles one with very deep orthography.
